### ISSUE TITLE
LED 색상 관련

### ISSUE THREAD

**Issue by SunWng** [lhanj2/qmk_firmware_#1]
안녕하세요, 올려주신 펌웨어를 사용해보고 있습니다.

일단 감사의 말씀 드립니다.

사용 중에 LED 색을 변경해도 좌측에 특정 부위는 분홍색으로 일정한데 펌웨어 자체의 오류일까요?

**Comment by lhanj2** [comment]
안녕하세요 음 RGB 조명관련 부분은 Jonavin  키코드를 사용했는데  측면 LED가 좌우 각각 5개의 아웃풋으로 제어되는걸로 기억합니다색상 관련 부분은 특히 자세히 보질 않아서 분홍색으로 고정되는 부분이 있다면 아마 조명 모드 중에 해당 부분을 분홍색으로 켜고 이후 좌측면 조명 5개 부분 중 하나를 제어하는 부분이 빠져 있지 않은가 하는 생각이 드네요 위 내용들은 나중에 한번 더 업데이트 하게 되면 확인해 보고 수정이 가능하면 수정해 보도록 하겠습니다Num Lock on 상태 or 캡스락 on 일 때에도 좌측 측면 LED가 고정되는 코드가 포함되어 있으니 이 부분도 한번 레이어를 이동하시면서 확인해 보시면 좋을 것 같습니다(Num Lock 키는 기본상태 On일 가능성도 있기 때문입니다.)FN키 입력은 우측 측면 LED가 들어오게 되어 있습니다.확인해 보시고 이후에도 같은 증상이면 알려주식고, Num Lock 때문이면 기본상태를 LED Off로 고정시키는 업데이트를 하면 되겠네요우선은 일차적으로 Num Lock 키가 On상태이기 때문으로 생각됩니다.내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: SunWng ***@***.***> 날짜: 21/8/8  오후 11:17  (GMT+09:00) 받은 사람: lhanj2/qmk_firmware_ ***@***.***> 참조: Subscribed ***@***.***> 제목: [lhanj2/qmk_firmware_] LED 색상 관련 (#1) 

안녕하세요, 올려주신 펌웨어를 사용해보고 있습니다.

일단 감사의 말씀 드립니다.

사용 중에 LED 색을 변경해도 좌측에 특정 부위는 분홍색으로 일정한데 펌웨어 자체의 오류일까요?

**Comment by lhanj2** [comment]
지금 코드를 확인해 보니 Num lock 관련 키를 매핑하지 않는 펌웨어네요주중에 시간나면 업데이트를 시도해 보겠습니다:)내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: SunWng ***@***.***> 날짜: 21/8/8  오후 11:17  (GMT+09:00) 받은 사람: lhanj2/qmk_firmware_ ***@***.***> 참조: Subscribed ***@***.***> 제목: [lhanj2/qmk_firmware_] LED 색상 관련 (#1) 

안녕하세요, 올려주신 펌웨어를 사용해보고 있습니다.

일단 감사의 말씀 드립니다.

사용 중에 LED 색을 변경해도 좌측에 특정 부위는 분홍색으로 일정한데 펌웨어 자체의 오류일까요?

**Comment by SunWng** [comment]
이 야밤에 감사합니다 선생님.

말씀해주신것처럼 기본 상태에 넘락이 켜져있던데 문제였습니다.

좀 더 찾아볼걸 그랬네요.

제가 qmk 사용이 처음이라 몇가지 궁금한게 있는데요,

- 글족의 경우에는 led, 노브 와 관련된 것만 via로 수정이 힘들어 보이던데 맞나요?

- led 관련한거 문제를 파악해보려고 소스코드를 열어봤는데, c로 되어있던데 qmk tutorial 페이지 보고 사용법을
익히신건가요??

- 마지막으로 제가 현재는 윈도우에서 powertoys를 사용해서 리눅스,맥,윈도우 환경에서 사용하는 단축키를 맞춰주고 있는데요
(예를들면 종료는 알트+Q, 탐색기는 알트+쉬프트+스페이스바) os가 달라져도 단축키와 수행되는 작업을 모두 같게 맵핑할 수 있나요??

궁금한게 더 많을 수 있을 것 같은데, 부담되실 수 있을 것 같아 이쯤만 적어서 보냅니다!

번거로우면 답변은 안해주셔도 됩니다.

아무쪼록 펌웨어 잘 사용하겠습니다.

감사합니다.

2021년 8월 8일 (일) 23:36, hjl ***@***.***>님이 작성:

**Comment by SunWng** [comment]
이 야밤에 감사합니다 선생님.

말씀해주신것처럼 기본 상태에 넘락이 켜져있던데 문제였습니다.

좀 더 찾아볼걸 그랬네요.

제가 qmk 사용이 처음이라 몇가지 궁금한게 있는데요,

- 글족의 경우에는 led, 노브 와 관련된 것만 via로 수정이 힘들어 보이던데 맞나요?

- led 관련한거 문제를 파악해보려고 소스코드를 열어봤는데, c로 되어있던데 qmk tutorial 페이지 보고 사용법을
익히신건가요??

- 마지막으로 제가 현재는 윈도우에서 powertoys를 사용해서 리눅스,맥,윈도우 환경에서 사용하는 단축키를 맞춰주고 있는데요
(예를들면 종료는 알트+Q, 탐색기는 알트+쉬프트+스페이스바) os가 달라져도 단축키와 수행되는 작업을 모두 같게 맵핑할 수 있나요??

궁금한게 더 많을 수 있을 것 같은데, 부담되실 수 있을 것 같아 이쯤만 적어서 보냅니다!

2021년 8월 8일 (일) 23:42, hjl ***@***.***>님이 작성:

**Comment by lhanj2** [comment]
1. 맞습니다2. qmk docs 사이트에서 키코드랑 기타 기본적인 것들 참고했습니다. 예제는 많이 없더라구요3. 이 경우는 위 사이트에서 여러 OS에서 같은 동작이라도 동일한 키코드가 있고 아닌 경우가 있어서 어려울 것 같습니다.만약 os별 전체 키보드 매핑이 목표라면레이어를 여러개 만들고 FN처럼 누르는 상태가 아닌 노브 레이어처럼 토글방식 래이어를 사용해서 키맵을 3가지로 만들면 충분히 가능할 것 같습니다.아마도 리눅스, 윈도우, 맥 레이어를 FN + 노브 키 등으로 매핑하여 전환하는 방법을 사용해도 좋을 것 같습니다흑.. 근데 저도 Qmk를 사용해본지 3일밖에 안되서 의문이 되는 상황이 꽤 있습니다.- 특정 기능 키에서만 먹히는 토글 명령어 같은게 존재합니다 예를 들면, 볼륨 조정은 쉬프트 + 노브로 사용하는데이 경우 쉬프트 키의 기능을 다른 문자 키에 매핑하면 안먹히는 상황이 발생하는 경우가 있습니다내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: SunWng ***@***.***> 날짜: 21/8/8  오후 11:46  (GMT+09:00) 받은 사람: lhanj2/qmk_firmware_ ***@***.***> 참조: hjl ***@***.***>, Comment ***@***.***> 제목: Re: [lhanj2/qmk_firmware_] LED 색상 관련 (#1) 
이 야밤에 감사합니다 선생님.



말씀해주신것처럼 기본 상태에 넘락이 켜져있던데 문제였습니다.



좀 더 찾아볼걸 그랬네요.



제가 qmk 사용이 처음이라 몇가지 궁금한게 있는데요,



- 글족의 경우에는 led, 노브 와 관련된 것만 via로 수정이 힘들어 보이던데 맞나요?



- led 관련한거 문제를 파악해보려고 소스코드를 열어봤는데, c로 되어있던데 qmk tutorial 페이지 보고 사용법을

익히신건가요??



- 마지막으로 제가 현재는 윈도우에서 powertoys를 사용해서 리눅스,맥,윈도우 환경에서 사용하는 단축키를 맞춰주고 있는데요

(예를들면 종료는 알트+Q, 탐색기는 알트+쉬프트+스페이스바) os가 달라져도 단축키와 수행되는 작업을 모두 같게 맵핑할 수 있나요??



궁금한게 더 많을 수 있을 것 같은데, 부담되실 수 있을 것 같아 이쯤만 적어서 보냅니다!



2021년 8월 8일 (일) 23:42, hjl ***@***.***>님이 작성:

**Comment by SunWng** [comment]
좀 더 뜯어봐야겠네요.

잘 알려주셔서 감사합니다 ㅎㅎ

2021년 8월 9일 (월) 07:26, hjl ***@***.***>님이 작성:

**Comment by lhanj2** [comment]
지금 보니 mykey/keymaps.c 파일도 최신 상태가 아니네요 ㅡ.ㅡ  폴더 복사하고 옮기다 꼬여서 연동이 제대로 안되네요
